### ISSUE TITLE
iPhone 5s global offset iOS 11.4.1

### ISSUE THREAD

**Issue by ABKasimy** [userlandkernel/jailbreakme-unified#15]
Credits
	Offset finder: Sem Voigtländer
	UI: iSn0w

Dyld Shared Cache Slide (ignore):
 0x2b50000

disablePrimitiveGigacage: 
0x18854ca8c

callbacks: 
0x1b33256a0

g_gigacageBasePtrs: 
0x1b1d6c000

g_typedArrayPoisons: 
0x1b3325728

longjmp: 
0x180b126e8

dlsym: 
0x18084ef90

startOfExecutableMemoryPool: 
0x1b33250b8

endOfExecutableMemoryPool: 
0x1b33250c0

jitWriteSeperateHeapsFunction: 
0x1b33250c8

useFastPermissionsJITCopy: 
0x1b1d68018

stack_check_guard: 
0x1b327fef8

LinkCode Gadget: 
0x187bf2fb4

**Comment by userlandkernel** [comment]
Thanks, I'll have a look.
Sadly I've terminated the public life of the project, but thanks for contributing in some way.
