### ISSUE TITLE
ios 8.4.1 iPod 5 

### ISSUE THREAD

**Issue by Aurous** [userlandkernel/jailbreakme-unified#16]
https://racecondition.win
exception occured:

Stack trace:

sploit_init@https://racecondition.win/modules/libsploit.strategy.module.js:102:33
sploit_init@https://racecondition.win/modules/libsploit.strategy.module.js:261:24
go@https://racecondition.win/:159:28
go@https://racecondition.win/:195:28
onchange@https://racecondition.win/:225:3

Reason: Can't find variable:
current_device

**Comment by userlandkernel** [comment]
Hmm, thanks. That's very useful, I'll try to fix it.
Though not publicly, I'm terminating the project in the public.
